### ISSUE TITLE
sdk version problem

### ISSUE THREAD

**Issue by AliRn76** [theswerd/InvertColors#1]
Hi I couldn't use this package, I get error below:

depends on invert_colors >=0.0.2 which requires Flutter SDK version >=1.20.0 <2.0.0, version solving failed.

**Comment by AliRn76** [comment]
Lol this means , I should upgrade my own sdk , Oops

**Comment by theswerd** [comment]
@AliRn76 sorry about that -- when I tried to publish with a lower requirement for dart pub.dev wouldn't let me.
